### ISSUE TITLE
Commit 1753363 changes AL scores for audio input

### ISSUE THREAD

**Issue by patrick-wilken** [facebookresearch/SimulEval#13]
In commit 1753363, `AudioInstance` was changed to use the base class function `Instance.sentence_level_eval()`. This introduced the bug (?) that 1 is added to `self.source_length()` also for the audio input case. (For text input, this is added because of sentence end).

This corresponds to 1ms only, however this changes the `lagging_padding_mask` in `AverageLagging`: all words predicted at the end of the sentence, i.e. after all audio was read, are now not taken into account for the AL computation. I observed the AL value to change from **5598ms to 3267ms** for a very high latency system where most of the words are predicted at sentence end.

See the line:

`lagging_padding_mask = delays >= src_lens.unsqueeze(1)`

`src_lens` is now 1 greater than `delays[-1]`, i.e. the audio length.

I think the old behaviour was correct, but please decide yourself 😬

**Comment by xutaima** [comment]
Hi Patrick. thank you so much for reporting and sorry for the late updates, we fixed this bug in 2f95899. Feel free to let me know if you have any further questions.

**Comment by patrick-wilken** [comment]
Yes, looks good :)
