### ISSUE TITLE
ReadAction and WriteAction

### ISSUE THREAD

**Issue by ZechengLi19** [facebookresearch/SimulEval#79]
Thanks for your awesome work. However, I am confused by how ReadAction and WriteAction affect model input and output. I can't find this part of the code.

Thanks!

**Comment by xutaima** [comment]
Hi @ZechengLi19, sorry for the late response. 

When a `ReadAction` is returned, the model will not generate output. Instead, more source input will be read and the states (e.g. `states.source` will include the next input) will be updated before the next time the `policy` function is called.

When a `WriteAction` is returned, the model will generate output. The evaluator will receive the output and track the delay of the output. The output will also update the states (e.g. `states.target`)

Hope this answers your question.

**Comment by ZechengLi19** [comment]
> Hi @ZechengLi19, sorry for the late response.
> 
> When a `ReadAction` is returned, the model will not generate output. Instead, more source input will be read and the states (e.g. `states.source` will include the next input) will be updated before the next time the `policy` function is called.
> 
> When a `WriteAction` is returned, the model will generate output. The evaluator will receive the output and track the delay of the output. The output will also update the states (e.g. `states.target`)
> 
> Hope this answers your question.

This simple and clear answer helped me a lot! 

Thanks for your reply!
