### ISSUE TITLE
bug in AL calculation

### ISSUE THREAD

**Issue by danliu2** [facebookresearch/SimulEval#8]
https://github.com/facebookresearch/SimulEval/blob/927072ebb7df83023adcc206b7458bf9c9aad3a2/simuleval/metrics/latency.py#L105

Dear developers,
       I just updated simuleval from 0.1.0 to newest version, and got signifitianlty lower AL score compared to older version. And here I found you made a small bug, range oracle_latency as range(1, ref_len+1), but based on AL definition in your paper, $d_i^{*}$ should be $(i-1)*\gamma$, thansk a lot.

**Comment by xutaima** [comment]
@danliu2 Thank you so much for reporting the bug. Now it's fixed by 43d61be. Feel free to let know if there is any problems.
