### ISSUE TITLE
Error during Simul ST(MuST-C) Evaluation

### ISSUE THREAD

**Issue by mzaidi59** [facebookresearch/SimulEval#9]
Following the steps in this [guide](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/simulst_mustc_example.md), I got this error when trying to evaluate the simultaneous speech-to-text model.

```
2021-03-12 13:03:29 | ERROR    | simuleval.util.agent_builder | No 'Agent' class found in /project_scratch/nmt_shdata/speech_translation/simultaneous/fairseq-master/examples/speech_to_text/simultaneous_translation/agents/fairseq_simul_st_agent.py
```
[This commit](https://github.com/pytorch/fairseq/commit/73886ac228f8f0368871237f7498ec8b07444322?branch=73886ac228f8f0368871237f7498ec8b07444322&diff=split) in the fairseq repo changed the superclass of the ST Agent, hence this error(due to the following if statement) 

https://github.com/facebookresearch/SimulEval/blob/927072ebb7df83023adcc206b7458bf9c9aad3a2/simuleval/utils/agent_finder.py#L71

-----
Environment
- python 3.8.5
- torch - 1.7.0
- OS: Linux
- fairseq and SimulEval - master codes
- Scripts: Provided in the [guide](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/simulst_mustc_example.md)

**Comment by jmp84** [comment]
@mzaidi59 I can reproduce this error, thanks for the report.

**Comment by xutaima** [comment]
Hi @mzaidi59, this is an issue of the example in fairseq and [this commit](https://github.com/pytorch/fairseq/commit/252d5a9ae93e68254cfb1896fb5624cf11cda15e) fixed it.

**Comment by mzaidi59** [comment]
Thank you for the quick response @xutaima & @jmp84
